apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: fastapi
  template:
    metadata:
      labels:
        component: fastapi
    spec:
      containers:
        - name: fastapi
          image: 'tsadimas/fastapi:2022nr'
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: fastapi-config
          env:
            - name: MYPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: mypassord
          volumeMounts:
            - name: data
              mountPath: /data
            - name: sqlvolume
              mountPath: "/sql"
              readOnly: true
      initContainers:
        - name: init-fastapi
          image: busybox
          command: ['sh', '-c', 'addgroup --gid 101 appuser && adduser --uid 100 -D -G appuser appuser && chown -R appuser:appuser /data ']
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: fastapidata
        - name: sqlvolume
          secret:
            secretName: sqlfilesecret
            items:
              - key: init.sql
                path: start.sql